### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by StinkyOnion03** [KidiXDev/TrackMyPlaytime#1] opened 2023-06-15 04:39 UTC
**Describe the bug**
when i play a game, the software crashing for no reason, and not track my playtime. pls help

**To Reproduce**
1. open tmp.exe
2. choose play button
3. then, software crash
4. done:)

**Comment by KidiXDev** [comment] 2023-06-15 04:43
I'll try to find out and fix it, did the crash happen when you first run the program?

**Comment by StinkyOnion03** [comment] 2023-06-15 04:45
> I'll try to find out and fix it, did the crash happen when you first run the program?

yes, first run program

**Comment by KidiXDev** [comment] 2023-06-15 05:11
its look like caused by the textractor launch, If you don't enter the directory of the textractor and you run the game that the textractor should be running at the same time, it will cause a crash, the code above should be fixed

```
private void textractorExec(GameList game)
{
    new Thread(() =>
    {    
        try
        {
            if (!setting.DisableTextractor && !game.DisableTextractor)
            {
                Thread.Sleep(setting.TextractorDelay);
                var textractorProc = new Process();
                if (game.ProgramType.Equals("x86"))
                {
                    textractorProc.StartInfo.FileName = setting.x86Directory;
                    textractorProc.StartInfo.WorkingDirectory = Path.GetDirectoryName(setting.x86Directory);
                    textractorProc.Start();
                }
                else
                {
                    textractorProc.StartInfo.FileName = setting.x64Directory;
                    textractorProc.StartInfo.WorkingDirectory = Path.GetDirectoryName(setting.x64Directory);
                    textractorProc.Start();
                }
            }
        }
        catch (Exception e)
        {
            MessageBox.Show($"Failed launch Textractor\nInfo{e.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            log.Error("Failed launch Textractor", e);
        }
    }).Start();
    
}

**Comment by KidiXDev** [comment] 2023-06-15 05:15
> I'll try to find out and fix it, did the crash happen when you first run the program?
> yes, first run program

To fix the problem you should check the Disable Texttractor option in the settings menu.

**Closed as completed** 2023-06-16 06:07 UTC
Labels: bug
